/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ua.goit;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String json = "{\"name\":\"Jhon\", \"age\":35, \"married\":true}";

        ObjectMapper mapper = new ObjectMapper();
        Customer customer;
        try {
            customer = mapper.readValue(json, Customer.class);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
        System.out.println("customer = " + customer);
    }
}
